docs: add english transalations of home
eggjs/egg pull request #4890
Opened 2022-02-17 10:14 UTC by zgayjjf

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2022-02-17 10:28 UTC, thonatos requested changes

2022-02-17 10:28 UTC, thonatos commented on site/docs/index.md
> +    title: Taobao NPM mirror is calling you to switch to new domain
cnpm 主要针对中文区，应该是可以不翻译的

2022-02-18 02:58 UTC, zgayjjf commented on site/docs/index.md
> +    title: Taobao NPM mirror is calling you to switch to new domain
虽然是这样，但是英文网站上显示中文，感觉还是不够味儿。
就好像一个其他项目，英文网站突然出现一句阿拉伯语似的 :P

2022-02-21 01:38 UTC, thonatos approved these changes

2022-02-21 01:39 UTC, merged